# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * MON"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
    - run: node .
      env:
        CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    - run: |
        git add users-stat.json
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m "Update users stat"
        git push

